[project]
name = 'forgetools'
version = '2025.06.16'
requires-python = '>=3.11'

[tool.ruff]
line-length = 79
format.quote-style = 'single'
isort.combine-as-imports = true
extend-select = ['I']  # isort
